### ISSUE TITLE
Add resource exclusions

### ISSUE THREAD

**Issue by mclarke47** [smoketurner/dropwizard-zipkin#19]
We have various status endpoints on our applications which I'd love to be able to exclude. Do you have a recommended way to achieve this? Perhaps some exclusions could be included in the config?

e.g.
```
...
exclude:
   -  */somecheck/*
   -  */someothercheck/
```

(Great job btw!)

**Comment by adriancole** [comment]
The new api in Brave 4+ supports dynamic sampling
<https://github.com/openzipkin/brave/tree/master/brave#custom-sampling>,
although we haven't yet migrated all instrumentation
<https://github.com/openzipkin/brave/issues/180#issuecomment-275033564> to
use it.

In the mean time, what you're asking could be accomplished by adding a
filter in front of the brave one that adds 'X-B3-Sampled: 0' when
`X-B3-Sampled` is absent on a path you want to skip. When Brave sees that,
it won't trace.

**Comment by mclarke47** [comment]
@adriancole thanks for the response. Do you have any examples I could use to get started?

**Comment by adriancole** [comment]
@jplock do you know how server resources are wired for tracing in DW? that would help narrow down how or what to use to insert a header

**Comment by jplock** [comment]
The Jersey way of probably doing this would be to have an additional annotation on the resource paths to exclude sampling.  I'm not exactly sure how we'd tie that into the Brave instance though since a single one is created upon startup and then filters are registered.  This might be something we have to introduce within `brave-jersey` itself to support (including the new annotation).

**Comment by mclarke47** [comment]
I think [this issue](https://github.com/openzipkin/brave/issues/303) was looking at a possible solution.
