### ISSUE TITLE
Support for jersey HttpRequestRetryHandler

### ISSUE THREAD

**Issue by youngpayters** [smoketurner/dropwizard-zipkin#49]
Currently this library doesn't seem to support custom retry handling. Would be great if this was added.

**Comment by adriancole** [comment]
if this is done, we should be careful to use a different span and not set
headers at the layer of abstraction that does retries.. or make sure the
span ID changes for each attempt. Otherwise, the same server can see the
same span ID twice which leads to problems in the tree and also analytical
problems.

>
